"""Tracking-source boundary for future phone and FR24 sources."""

from collections.abc import Callable
from typing import Any, Protocol


class TrackingSource(Protocol):
    async def async_start(self, identifier: str) -> None: ...
    async def async_stop(self, identifier: str) -> None: ...
    async def async_setup(self, on_update: Callable[[], None]) -> None: ...
    async def async_shutdown(self) -> None: ...
    @property
    def available(self) -> bool: ...
    @property
    def flights(self) -> list[dict[str, Any]]: ...
